language: c

# Based from: https://github.com/greghendershott/travis-racket

# Optional: Remove to use Travis CI's older infrastructure.
sudo: false

env:
  global:
    # Supply a global RACKET_DIR environment variable. This is where
    # Racket will be installed. A good idea is to use ~/racket because
    # that doesn't require sudo to install and is therefore compatible
    # with Travis CI's newer container infrastructure.
    - RACKET_DIR=~/racket
  matrix:
    # Supply at least one RACKET_VERSION environment variable. This is
    # used by the install-racket.sh script (run at before_install,
    # below) to select the version of Racket to download and install.
    #
    # Supply more than one RACKET_VERSION (as in the example below) to
    # create a Travis-CI build matrix to test against multiple Racket
    # versions.
    - RACKET_VERSION=6.7    COVER=false
    - RACKET_VERSION=6.8    COVER=false
    - RACKET_VERSION=6.9    COVER=true
    - RACKET_VERSION=6.10   COVER=true
    - RACKET_VERSION=6.10.1 COVER=true
    - RACKET_VERSION=6.11   COVER=true
    - RACKET_VERSION=6.12   COVER=true
    - RACKET_VERSION=7.0    COVER=true
    - RACKET_VERSION=7.1    COVER=true
    - RACKET_VERSION=7.2    COVER=true
    - RACKET_VERSION=HEAD   COVER=true

matrix:
  allow_failures:
#   - env: RACKET_VERSION=HEAD
  fast_finish: true

before_install:
- git clone https://github.com/greghendershott/travis-racket.git ~/travis-racket
- cat ~/travis-racket/install-racket.sh | bash # pipe to bash not sh!
- export PATH="${RACKET_DIR}/bin:${PATH}" #install-racket.sh can't set for us

install:
 - raco pkg install --deps search-auto

before_script:

# Here supply steps such as raco make, raco test, etc.  You can run
# `raco pkg install --deps search-auto` to install any required
# packages without it getting stuck on a confirmation prompt.
script:
 - raco test -p tr-immutable
 - raco setup --check-pkg-deps --pkgs tr-immutable
 - if $COVER; then raco pkg install --deps search-auto doc-coverage; fi
 - if $COVER; then raco doc-coverage tr-immutable; fi
 - if $COVER; then raco pkg install --deps search-auto cover cover-codecov; fi
 - if $COVER; then raco cover -s doc -s test -s main -f codecov -d $TRAVIS_BUILD_DIR/coverage .; fi

after_success:
